nobase_motr_include_HEADERS += fid/fid.h \
                               fid/fid_list.h

motr_libmotr_la_SOURCES += fid/fid.c \
                           fid/fid_list.c

nodist_motr_libmotr_la_SOURCES  += fid/fid_xc.c

XC_FILES   += fid/fid_xc.h
