#!/usr/bin/env bash
#
# Copyright (c) 2020 Seagate Technology LLC and/or its Affiliates
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# For any questions about this software or licensing,
# please email opensource@seagate.com or cortx-questions@seagate.com.
#


# exit immediately if one the commands exits with a non-zero status
set -e

# constants
readonly PROG_NAME=$(basename $0)

# global variables, which can be overriden in /etc/sysconfig/motr
MOTR_GENDERS_CONF=/etc/motr/genders

# service local variables
service_funcs=/usr/libexec/cortx-motr/motr-service.functions

m0_dixinit()
{
    source $service_funcs

    # read configs
    [[ -r $kernel_config ]] && source $kernel_config
    [[ -r $user_config ]]   && source $user_config

    [[ -n "$MOTR_M0D_DEBUGGER" ]] && export M0_DEBUGGER=$MOTR_M0D_DEBUGGER

    m0_cas_enabled || {
        m0_log 'CAS service is not enabled, skipping m0dixinit'
        return 0
    }

    local service_dir=$(m0_get_m0d_data_dir_for dixinit)
    [[ ! -d $service_dir ]] && mkdir -p "$service_dir"
    cd "$service_dir"

    local ha_ep=${MOTR_HA_EP:-$(m0_get_global_ep_of ha)}
    local dix_pverid='v|1:20'
    local dixinit=$(m0_path_to m0dixinit)

    m0_run $dixinit -l $(m0_get_lnet_nid):12345:34:101 -H $ha_ep \
                    -p $m0_prof_opt -I $dix_pverid \
                    -d $dix_pverid -a create
}

# Skip m0dixinit, mkfs creates meta indices now. See MOTR-2793.
# m0_dixinit
