nobase_motr_include_HEADERS += \
                               graph/graph.h

motr_libmotr_la_SOURCES  += \
                            graph/graph.c

nodist_motr_libmotr_la_SOURCES  += graph/graph_xc.c

XC_FILES   += graph/graph_xc.h
