#!/usr/bin/env bash
#
# Copyright (c) 2020 Seagate Technology LLC and/or its Affiliates
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# For any questions about this software or licensing,
# please email opensource@seagate.com or cortx-questions@seagate.com.
#

set -e
#set -x

SCRIPT_PATH="$(realpath $0)"
SCRIPT_DIR="${SCRIPT_PATH%/*}"

. ${SCRIPT_DIR}/common/remote_execution

SRV_CLI_MAP=$1
WORKLOAD=$2

trap set_term_flag SIGTERM

function main()
{
    parse_nodes
    check_required_parameters

    local iter=0

    while [[ -z "$TERMINATE_FLAG" ]]; do
        sleep 20
        echo -e "============== start iteration $iter ($(date)) ================\n"
        set +e
        $EX_SRV $SCRIPT_DIR/s3server_integration/s3cli_s3bench \"$SRV_CLI_MAP\" \"$WORKLOAD\"
        set -e
        echo -e "============== end iteration $iter ($(date)) ================\n\n"
        iter=$((iter+1))
    done
}

function set_term_flag()
{
    echo "got termination request"
    TERMINATE_FLAG=1
}

function check_required_parameters()
{
    if [[ -z "$SRV_CLI_MAP" || -z "$WORKLOAD" ]]; then
        echo "missed required parameter"
        echo "Usage: ./endless_s3bench $SRV_CLI_MAP $workload"
        exit 1
    fi
}

main
exit $?
