#!/usr/bin/env bash
#
# Copyright (c) 2020 Seagate Technology LLC and/or its Affiliates
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# For any questions about this software or licensing,
# please email opensource@seagate.com or cortx-questions@seagate.com.
#

set -x
set -e

FIO_TESTS_DIR=$1
FIO_RESULTS_DIR="/tmp/fio_results"

function run_fio_tests() {
    mkdir -p $FIO_RESULTS_DIR
    rm -f $FIO_RESULTS_DIR/*

    for fio_test in $(ls $FIO_TESTS_DIR | grep `hostname -s`); do
        fio $FIO_TESTS_DIR/$fio_test > $FIO_RESULTS_DIR/${fio_test}.txt
    done
}

run_fio_tests
