nobase_motr_include_HEADERS += iscservice/isc_service.h \
                               iscservice/isc.h \
                               iscservice/isc_fops.h

motr_libmotr_la_SOURCES  += iscservice/isc_service.c \
                            iscservice/isc.c \
                            iscservice/isc_fops.c

nodist_motr_libmotr_la_SOURCES  += \
                            iscservice/isc_fops_xc.c

XC_FILES   += iscservice/isc_fops_xc.h
