nobase_motr_include_HEADERS += fol/fol.h \
                               fol/fol_private.h

motr_libmotr_la_SOURCES  += fol/fol.c

nodist_motr_libmotr_la_SOURCES  += fol/fol_xc.c

XC_FILES   += fol/fol_xc.h
