#!/usr/bin/env bash
#
# Copyright (c) 2020 Seagate Technology LLC and/or its Affiliates
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# For any questions about this software or licensing,
# please email opensource@seagate.com or cortx-questions@seagate.com.
#

set -x
set -e

SCRIPT_PATH="$(realpath $0)"
SCRIPT_DIR="${SCRIPT_PATH%/*}"

. ${SCRIPT_DIR}/../common/common_funcs

S3_CRED_FILE="${SCRIPT_DIR}/s3_credentials_$(hostname -s)"
LDAP_USER="sgiamadmin"
LDAP_PASS="ldapadmin"

function check_and_create_s3_cred() {
    if [[ ! -f "$S3_CRED_FILE" ]]; then
        _info "creation s3 credentials in $S3_CRED_FILE"

        local rnd_str=`dd if=/dev/urandom bs=1024 count=1 2>/dev/null \
            | tr -dc a-z | head -c10`
        local hostname=$(hostname -s)
        local username="perf_${hostname}_${rnd_str}"

        $SCRIPT_DIR/s3_create_user --name $username \
            --email ${username}@seagate.com --ldap-user $LDAP_USER \
            --ldap-pass $LDAP_PASS > $S3_CRED_FILE
    fi
}

if [[ -z "$S3_CRED_FILE" ]]; then
    _err "path to credentials file hasn't been specified"
    exit 1
fi

check_and_create_s3_cred
