#!/usr/bin/env bash
#
# Copyright (c) 2020 Seagate Technology LLC and/or its Affiliates
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# For any questions about this software or licensing,
# please email opensource@seagate.com or cortx-questions@seagate.com.
#

set -x
set -e

SCRIPT_PATH="$(readlink -f $0)"
SCRIPT_DIR="${SCRIPT_PATH%/*}"

. ${SCRIPT_DIR}/../common/common_funcs
. ${SCRIPT_DIR}/functions

S3_SRV_CLI_MAP=$1

function create_bucket() {
    local aws_bin="/usr/local/bin/aws"
    local bucket="seagatebucket-$(hostname -s)"
    $EX_CLI "$aws_bin s3 ls s3://$bucket &> /dev/null || $aws_bin s3 mb s3://$bucket"
}

if [[ -z "$S3_SRV_CLI_MAP" ]]; then
        _err "servers-clients map wasn't specified"
        exit 1
fi

parse_s3_nodes_map $S3_SRV_CLI_MAP

if [ -z "$CLI_NODES" ]; then
    exit 0
fi

EX_CLI="pdsh -S -w $CLI_NODES"

create_bucket
