#!/usr/bin/env bash
#
# Copyright (c) 2020 Seagate Technology LLC and/or its Affiliates
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# For any questions about this software or licensing,
# please email opensource@seagate.com or cortx-questions@seagate.com.
#

set -e

#
# Wrapper script for Jenkins test '03initscript-tests'
#

M0_SRC_DIR=`readlink -f $0`
M0_SRC_DIR=${M0_SRC_DIR%/*/*}

currdir=$(pwd)
SANITY_SANDBOX_DIR="/var/motr/sanity_$timestamp"
. $M0_SRC_DIR/utils/functions # report_and_exit

cd $M0_SRC_DIR
start_singlenode()
{
	mkdir -p "$SANITY_SANDBOX_DIR"
	cd "$SANITY_SANDBOX_DIR"

	# setup motr singlenode
	$M0_SRC_DIR/utils/m0singlenode activate
	$M0_SRC_DIR/utils/m0setup -cv -d "$SANITY_SANDBOX_DIR" -m "$SANITY_SANDBOX_DIR"
	$M0_SRC_DIR/utils/m0setup -N 1 -K 0 -S 0 -P 8 -s 8 -Mv -d "$SANITY_SANDBOX_DIR" \
		-m "$SANITY_SANDBOX_DIR" --no-m0t1fs

	# start motr
	$M0_SRC_DIR/utils/m0singlenode start
}

stop_singlenode()
{
	# stop motr
	$M0_SRC_DIR/utils/m0singlenode stop
	$M0_SRC_DIR/utils/m0setup -cv -d "$SANITY_SANDBOX_DIR" -m "$SANITY_SANDBOX_DIR"
	cd "$currdir"

	# cleanup remaining motr-services
	systemctl start motr-cleanup

	# remove sanity test sandbox directory
	if [[ "$1" == "cleanup" ]]
	then
		rm -rf "$SANITY_SANDBOX_DIR"
	fi
}
sudo ./scripts/install-motr-service -u
sudo ./scripts/install-motr-service -l

start_singlenode
echo "=================================================="
echo "========Motr singlenode services started=========="
echo "=================================================="
stop_singlenode "cleanup"
echo "=================================================="
echo "========Motr singlenode services stopped=========="
echo "=================================================="


report_and_exit initscripts $?
