#!/usr/bin/env bash
#
# Copyright (c) 2020 Seagate Technology LLC and/or its Affiliates
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# For any questions about this software or licensing,
# please email opensource@seagate.com or cortx-questions@seagate.com.
#


#
# This script compares two xcode protocol files specified by ARGS
#

set -e

M0_SRC_DIR=`realpath $0`
M0_SRC_DIR=${M0_SRC_DIR%/*/*}

. $M0_SRC_DIR/utils/functions # report_and_exit

cd $M0_SRC_DIR

diff_cmd='diff -u'
if which wdiff 2>/dev/null ; then
    diff_cmd='wdiff'
fi

proto_current="$M0_SRC_DIR/xcode/protocol.txt"
proto_prod="http://cortx-storage.colo.seagate.com/releases/cortx/github/main/"
proto_prod+="rockylinux-8.4/last_successful_prod/cortx_iso/"
test_dir="/tmp/37protocol-test"
proto_dev="${test_dir}/usr/share/motr/protocol.txt"

# remove old st dir if already exists
rm -rf $test_dir 2>&1> /dev/null

# create st dir if does not exists
mkdir -p $test_dir

pushd $test_dir
echo "Downloading latest protocol file from prod"
wget -q -np -nd -r -P $test_dir -A "cortx-motr-[0-9]*_git*.x86_64.rpm" $proto_prod
rpm2cpio cortx-motr*.rpm | cpio -id
popd

echo "Comparing '$proto_dev' and '$proto_current' files"
$diff_cmd $proto_dev $proto_current
exit_code=$?
if [ $exit_code -ne 0 ]; then
    echo -n "37protocol ST may fail if there are some local changes done to "
    echo -n "the BE structures. Please confirm these are intended changes to "
    echo "the BE structures in the new version before ignoring this error."
fi

# remove test files
rm -rf $test_dir 2>&1> /dev/null

report_and_exit initscripts $exit_code
