#!/usr/bin/env bash
#
# Copyright (c) 2020 Seagate Technology LLC and/or its Affiliates
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# For any questions about this software or licensing,
# please email opensource@seagate.com or cortx-questions@seagate.com.
#

set -e

#
# Test Motr rpm update and interoperability
#

readonly PROG_NAME=$(basename $0)
M0_SRC_DIR=$(readlink -f $0)
M0_SRC_DIR=${M0_SRC_DIR%/*/*}

. $M0_SRC_DIR/utils/functions # report_and_exit

usage()
{
    cat <<USAGE_END
Usage: $PROG_NAME motr-x1.y1.z1.rpm motr-x2.y2.z2.rpm
USAGE_END
}

die()
{
    echo -e "$PROG_NAME:  ERROR:  $*" >&2
    exit 1
}

info()
{
    echo "$PROG_NAME:  INFO:   $*"
}

# sanity checks
if [[ -z "$1" || -z "$2" ]] ; then
    die "expected 2 arguments, provided $#\n" \
        $(usage)
fi

info "Installing base rpm '$1'"
sudo $M0_SRC_DIR/st/m0t1fs -vv --no-cleanup -r $1

info "Installing update '$2'"
sudo $M0_SRC_DIR/st/m0t1fs -vv -u -r $2

report_and_exit initscripts $?
