be_tool_m0betool_SOURCES = \
                           be/tool/common.c \
                           be/tool/main.c \
                           be/tool/st.c

#TBD: Uncomment this after CORTX-32593 is fixed.
#be_tool_m0beck_SOURCES = be/tool/beck.c

EXTRA_DIST += \
              be/tool/common.h \
              be/tool/st.h
