#!/usr/bin/env bash
#
# Copyright (c) 2020 Seagate Technology LLC and/or its Affiliates
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# For any questions about this software or licensing,
# please email opensource@seagate.com or cortx-questions@seagate.com.
#


function parse_nodes() {
    for map in $SRV_CLI_MAP; do
        local srv=$(echo $map | awk -F '=' '{print $1}')
        local cli=$(echo $map | awk -F '=' '{print $2}')

        if [[ -n "$srv" ]]; then
            if [[ -z "$SRV_NODES" ]]; then
                SRV_NODES="$srv"
            else
                SRV_NODES="$SRV_NODES,$srv"
            fi
        fi

        if [[ -n "$cli" ]]; then
            if [[ -z "$CLI_NODES" ]]; then
                CLI_NODES="$cli"
            else
                CLI_NODES="$CLI_NODES,$cli"
            fi
        fi

    done

    if [[ -n "$SRV_NODES" ]]; then
        EX_SRV="pdsh -S -w $SRV_NODES"
    else
        EX_SRV="eval"
    fi

    if [[ -n "$CLI_NODES" ]]; then
        EX_CLI="pdsh -S -w $CLI_NODES"
    else
        EX_CLI="eval"
    fi
}

function cluster_copy()
{
    if [[ -n "$SRV_NODES" ]]; then
        $EX_SRV scp -r "$1" $(hostname):$2
    else
        eval "local p1=$1"
        eval "local p2=$2"
        cp -r $p1 $p2
    fi
}

function client_copy()
{
    if [[ -n "$CLI_NODES" ]]; then
        $EX_CLI scp -r "$1" $(hostname):$2
    else
        eval "local p1=$1"
        eval "local p2=$2"
        cp -r $p1 $p2
    fi
}