#!/usr/bin/env bash
#
# Copyright (c) 2020 Seagate Technology LLC and/or its Affiliates
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# For any questions about this software or licensing,
# please email opensource@seagate.com or cortx-questions@seagate.com.
#

### wrapper to run user-space programs, which depend on m0tr kernel module
set -x
#
# Global vars
#

# constants
readonly PROG_NAME=$(basename $0)
readonly self=$(realpath $0)
readonly base_rundir='/var/motr'
readonly top_srcdir=$(echo $(dirname $self) \
                      | sed -r -e 's#/?utils/?$##' -e 's#^/usr/s?bin##')

M0_SRC_DIR=`readlink -f $0`
M0_SRC_DIR=${M0_SRC_DIR%/*/*}

. $M0_SRC_DIR/utils/functions # m0_default_xprt

XPRT=$(m0_default_xprt)
# variables
verbose=false
debugger=
force_modules_reload=false
rundir=$base_rundir
node_uuid=${M0_NODE_UUID:-00000000-0000-0000-0000-000000000000}
trace_level=${M0_TRACE_LEVEL:-notice+}
trace_immediate_mask=${M0_TRACE_MASK:-all}
trace_print_context=${M0_TRACE_PRINT_CONTEXT:-short}
cli_args=
binary=
gdbparams=${GDBPARAMS:-}
udebugger=${UDEBUGGER:-echo}

#
# Usage
#

help()
{
    [[ $1 == stdout ]] && usage || usage >&2
    exit 1
}

usage()
{
    cat <<USAGE_END
Usage: $PROG_NAME [options] <exec-file> [-- exec-options]

  Helper tool to run user-space programs, which depend on m0tr kernel module.
  It's possible to specify various Motr kernel module and user library parameters
  with command-line options. m0run starts LNet service and loads Motr kernel
  modules on start-up, before executing a user space program. On exit, Motr
  modules are unloaded, but LNet remains running. If Motr modules are already
  loaded then m0run doesn't touch them (i.e. doesn't reload on start and doesn't
  unload on exit). This is default behaviour, which can be changed with -f
  option (see below).

    <exec-file>   Name of executable to run, it should be either found in PATH
                  or have a symlink under 'utils/' in Motr source tree. If
                  options need to be passed to executable, they should be
                  specified after '--' token.

  Options:

    -f                  Force modules reloading. If Motr modules are already
                        loaded, this forces reload on start and unload on exit.
                        LNet service is restarted as well, but it's kept running
                        on exit. It works only for system-wide Motr
                        installation, otherwise this option is ignored.

    -r|--rundir         Where to run <exec-file> ($PROG_NAME will cd into this
                        dir), by default it's '$base_rundir'.

    -d[debugger], --debugger[=debugger]

                        Run <exec-file> under 'debugger'. If 'debugger' is
                        omitted, gdb is used by default. Valid debuggers are:
                        'gdb', 'cgdb', 'valgrind', 'valgrind-memcheck',
                        'valgrind-cachegrind', 'valgrind-callgrind',
                        'valgrind-helgrind', 'valgrind-drd', 'valgrind-massif',
                        'valgrind-exp-sgcheck', 'valgrind-exp-dhat',
                        'valgrind-exp-bbv' and 'user'.

    -l|--trace-level    Trace level (for both m0tr.ko and libmotr.so).
                        By default it's 'notice+'.

    -m|--trace-mask     Trace subsystem mask (for both m0tr.ko and libmotr.so).
                        By default it's 'all'.

    -c|--trace-ctx      Trace print context (for both m0tr.ko and libmotr.so).
                        By default it's 'short'.

    -u|--uuid           Node uuid for m0tr.ko.

    -v|--verbose        Print what's going on.

    -h|--help           Print this help screen.
USAGE_END
}

#
# Parse CLI options
#

parse_cli_options()
{
    # Note that we use `"$@"' to let each command-line parameter expand to a
    # separate word. The quotes around `$@' are essential!
    # We need TEMP as the `eval set --' would nuke the return value of getopt.
    # We need to separate TEMP declaration and assignment because 'local TEMP='
    # would nuke the return value of getopt.
    local TEMP
    TEMP=$( getopt -o hvfr:d::l:m:c:u: \
                   --long help,verbose,rundir:,debugger::,trace-level:,trace-mask:,trace-ctx:,uuid: \
                   -n "$PROG_NAME" -- "$@" )

    [[ $? != 0 ]] && help

    # Note the quotes around `$TEMP': they are essential!
    eval set -- "$TEMP"

    while true ; do
        case "$1" in
            -f)                 force_modules_reload=true; shift ;;
            -r|--rundir)        rundir=$2; shift 2 ;;
            -d|--debugger)      [[ -n "$2" ]] && debugger=$2 || debugger='gdb'; shift 2 ;;
            -l|--trace-level)   trace_level=$2; export M0_TRACE_LEVEL=$2; shift 2 ;;
            -m|--trace-mask)    trace_mask=$2; export M0_TRACE_MASK=$2; shift 2 ;;
            -c|--trace-ctx)     trace_ctx=$2; export M0_TRACE_PRINT_CONTEXT=$2; shift 2 ;;
            -u|-uuid)           node_uuid=$2; shift 2 ;;
            -v|--verbose)       verbose=true; shift ;;
            -h|--help)          help stdout ;;
            --)                 shift; break ;;
            *)                  echo 'getopt: internal error...'; exit 1 ;;
        esac
    done

    # remaining command line arguments
    cli_args="$@"
}

#
# Utility functions
#

die()
{
    echo "$PROG_NAME: ERROR: $@" >&2
    exit 1
}

log()
{
    ! $verbose || echo "$PROG_NAME: $@"
}

srcdir_path_of()
{
    local binary=$top_srcdir/utils/$1

    if [[ -z "$top_srcdir" ]] ; then
        echo $1
    elif [[ -L $binary ]] ; then
        echo "$top_srcdir/$(readlink $binary | sed -e 's#^../##')"
    fi
}

run_gdb()
{
    local gdbinit=${top_srcdir:+-x ${top_srcdir}/.gdbinit}

    log "gdb $gdbinit --args $binary $@"
    gdb $gdbinit $gdbparams --args $binary "$@"
}

run_cgdb()
{
    local gdbinit=${top_srcdir:+-x ${top_srcdir}/.gdbinit}

    log "cgdb $gdbinit --args $binary $@"
    cgdb $gdbinit --args $binary "$@"
}

run_user()
{
    echo "Running user debugger $udebugger (set '$UDEBUGGER' to change)."
    $udebugger $binary "$@"
}

run_valgrind_memcheck()
{
    log "valgrind" \
            "--tool=memcheck" \
            "--trace-children=yes --track-fds=yes" \
            "--leak-check=full --track-origins=yes" \
            "--show-leak-kinds=all" "--num-callers=32" \
            "--read-var-info=yes" \
            "$binary $@"
    valgrind \
        --tool=memcheck \
        --trace-children=yes --track-fds=yes \
        --leak-check=full --track-origins=yes \
        --show-leak-kinds=all --num-callers=32 \
        --read-var-info=yes \
        $binary "$@"
}

run_valgrind_cachegrind()
{
    log "valgrind --tool=cachegrind $binary $@"
    valgrind --tool=cachegrind $binary "$@"
}

run_valgrind_callgrind()
{
    log "valgrind --tool=callgrind $binary $@"
    valgrind --tool=callgrind $binary "$@"
}

run_valgrind_helgrind()
{
    log "valgrind --tool=helgrind --read-var-info=yes $binary $@"
    valgrind --tool=helgrind --read-var-info=yes $binary "$@"
}

run_valgrind_drd()
{
    log "valgrind --tool=drd --read-var-info=yes --free-is-write=yes $binary $@"
    valgrind --tool=drd --read-var-info=yes --free-is-write=yes $binary "$@"
}

run_valgrind_massif()
{
    log "valgrind --tool=massif $binary $@"
    valgrind --tool=massif $binary "$@"
}

run_valgrind_exp_sgcheck()
{
    log "valgrind --tool=exp-sgcheck $binary $@"
    valgrind --tool=exp-sgcheck $binary "$@"
}

run_valgrind_exp_dhat()
{
    log "valgrind --tool=exp-dhat $binary $@"
    valgrind --tool=exp-dhat $binary "$@"
}

run_valgrind_exp_bbv()
{
    log "valgrind --tool=exp-bbv $binary $@"
    valgrind --tool=exp-bbv $binary "$@"
}

run_valgrind()
{
    run_valgrind_memcheck "$@"
    echo
    run_valgrind_cachegrind "$@"
    echo
    run_valgrind_callgrind "$@"
    echo
    run_valgrind_helgrind "$@"
    echo
    #run_valgrind_drd "$@"
    #echo
    run_valgrind_massif "$@"
    echo
    #run_valgrind_exp_sgcheck "$@"
}

# Loads Motr modules either from source tree or system-wide, if source tree is
# not found.
load_modules()
{
    if [[ $(is_lnet_available) == "true" ]]; then
        if [[ -n "$top_srcdir" ]] ; then
            source $top_srcdir/utils/modload-all.sh
        else
            # don't try to load Motr modules if they already are
            # and don't unload them as well (EXIT trap is not set)
            # unless '-f' option was used
            local loaded=false
            if lsmod | grep -Eq 'm0' ; then
                log 'Motr kernel modules are already loaded'
                loaded=true
                if $force_modules_reload ; then
                    log 'forcing Motr modules reloading'
                    modprobe -r m0tr
                    loaded=false
                else
                    return 0
                fi
            fi

                local lnet_status=$(service lnet status)
                if $force_modules_reload || [[ $lnet_status != running ]] ; then
                    log '(re)starting LNet service'
                    service lnet stop
                    service lnet start
                fi

            if ! $loaded ; then
                log 'loading Motr modules'
                modprobe m0mtr  "node_uuid=$node_uuid" \
                                "trace_immediate_mask=$trace_immediate_mask" \
                                "trace_print_context=$trace_print_context" \
                                "trace_level=$trace_level"

                trap unload_modules EXIT
            fi
        fi
    fi
}

unload_modules()
{
    log 'unloading Motr modules'
    modprobe -r m0tr
}

#
# Main
#

# exit immediately if one the commands exits with a non-zero status
set -e

parse_cli_options "$@"
eval set -- "$cli_args"

[[ $UID -eq 0 ]] ||
    die 'Please, run this script with "root" privileges.'

binary=$1
[[ -n "$binary" ]] ||
    die "Please, specify which binary to run as a first command-line argument."
shift

if [[ -n "$top_srcdir" &&
      ! (-f $(srcdir_path_of $binary) && -x $(srcdir_path_of $binary)) ]] ||
   [[ -z "$top_srcdir" ]] && ! which $binary &>/dev/null
then
    die "'$binary' is not found or missing executable permissions."
fi

# for unit tests allow only 'fatal' and higher trace messages to be printed on
# console by default, to prevent cluttering of UT output with "fake" error
# messages, generated while testing various error paths using fault injection;
# this can be overridden with '-e' CLI option of `m0ut`.
if [[ $binary =~ .*m0ut(-isolated)?$ ]] ; then
    export M0_TRACE_LEVEL='fatal+'
fi

[[ $rundir != $base_rundir ]] || rundir="$base_rundir/$binary"

mkdir -p "$rundir"
log "cd '$rundir'"
cd "$rundir"

load_modules

# enable core dumps
ulimit -c unlimited
ulimit -n 65536

# Increase the maximum number of memory map areas a process may have.
# m0d process may allocate and madvise() at least 2,000,000 memory map areas.
# See MOTR-2171 for more details.
sysctl -q -w vm.max_map_count=30000000

if [[ -n "$debugger" ]] ; then
    # libmotr will attach debugger in case of panic, disable this as we already
    # going to run it under debugger
    unset M0_DEBUGGER

    if [[ -n "$top_srcdir" ]] ; then
        # nasty libtool creates wrapper shell scripts for non-installed
        # binaries and links them on first run under '.libs/' directory with
        # 'lt-' prefix
        lt_binary="$(dirname $(srcdir_path_of $binary))/.libs/lt-$binary"
        if [[ ! -x $lt_binary ]] ; then
            log "generating '$lt_binary' binary"
            set +e
            $(srcdir_path_of $binary) -h &> /dev/null
            set -e
        fi
        binary=$lt_binary
    fi

    case $debugger in
        gdb)                  run_gdb "$@" ;;
        cgdb)                 run_cgdb "$@" ;;
        user)                 run_user "$@" ;;
        valgrind)             run_valgrind "$@" ;;
        valgrind-memcheck)    run_valgrind_memcheck "$@" ;;
        valgrind-cachegrind)  run_valgrind_cachegrind "$@" ;;
        valgrind-callgrind)   run_valgrind_callgrind "$@" ;;
        valgrind-helgrind)    run_valgrind_helgrind "$@" ;;
        valgrind-drd)         run_valgrind_drd "$@" ;;
        valgrind-massif)      run_valgrind_massif "$@" ;;
        valgrind-exp-sgcheck) run_valgrind_exp_sgcheck "$@" ;;
        valgrind-exp-dhat)    run_valgrind_exp_dhat "$@" ;;
        valgrind-exp-bbv)     run_valgrind_exp_bbv "$@" ;;
        *)        die "unsupported debugger '$debugger'." ;;
    esac
else
    log "$(srcdir_path_of $binary) $@"
    # TODO: add output redirection (-o|--stdout, -O|--stdboth, -e|--stderr)
    $(srcdir_path_of $binary) "$@"
fi
