#!/usr/bin/env bash
#
# Copyright (c) 2020 Seagate Technology LLC and/or its Affiliates
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# For any questions about this software or licensing,
# please email opensource@seagate.com or cortx-questions@seagate.com.
#

set -eu

FILTER='tail -3'
INTERACTIVE=0
COLOR_1='\033[33m'          # fg=yellow
COLOR_2='\033[30m\033[47m'  # fg=black, bg=white
NO_COLOR='\033[0m'

die() { echo "$@" >&2; exit 1; }

url_dir() {
	echo -n "http://jenkins-fre.xyus.xyratex.com:8080/job/"
	echo "motr-test-gerrit/${1}/artifact/workdir/motr-single"
}

inter() { if [ $INTERACTIVE -eq 1 ]; then "$@"; fi; }

say() {
	inter echo -en "$COLOR_1"
	echo "$@"
	inter echo -en "$NO_COLOR"
}

usage() {
	cat <<EOF
Usage: ${0##*/} [OPTION]... <motr-test-gerrit #>...

Options:
    -i, --interactive    Pause after each test #.
    --full               Show full output (\`$FILTER' is used by default).
    -h, --help           Show this help and exit.
EOF
}

### ----------------------------------------------------------------------
### main
### ----------------------------------------------------------------------

while [ $# -gt 0 -a "${1#-}" != "$1" ]; do  # for each arg that starts with `-'
	case "$1" in
		-h|--help)        usage; exit 0;;
		-i|--interactive) INTERACTIVE=1; shift;;
		--full)           FILTER=cat; shift;;
		*) echo "Unknown option: $1" >&2; die "`usage`";;
	esac
done
[ $# -gt 0 ] || die "`usage`"

inter trap "echo -en '$NO_COLOR'" 0
for test_id in "$@"; do
	inter clear
	say "* $(url_dir $test_id)/"
	for f in 0{0userspace,1kernel,2system}-tests.\
{stdout,stderr,messages.colibri}.log; do
		say "** $f"
		wget -qO- "$(url_dir $test_id)/$f" | $FILTER
	done
	inter echo -en "$COLOR_2"
	inter read -p 'Press Enter to continue... '
	inter echo -en "$NO_COLOR"
done
