nobase_motr_include_HEADERS += reqh/reqh.h \
                               reqh/reqh_service.h

motr_libmotr_la_SOURCES  += reqh/reqh.c \
                            reqh/reqh_service.c \
                            reqh/reqh_service_internal.h
